ci: update workflow

diff --git a/.github/workflows/flake-bump.yaml b/.github/workflows/flake-bump.yaml
--- a/.github/workflows/flake-bump.yaml
+++ b/.github/workflows/flake-bump.yaml
@@ -24,23 +24,34 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install --upgrade gitlint
+    # this rule checks the prerequisits and write the exit code in its output
     - name: Lint git commit messages
       run: |
+        set +e
         gitlint --commits origin/$GITHUB_BASE_REF.. -C .gitlint_auto_approve
+        code=$?
+        echo "exit_code=$code" >> "$GITHUB_OUTPUT"
+        exit 0
 
   gitmerge:
     name: Merge flake bump
     needs: gitlint  # hard dependency on this check job
+    if: ${{ needs.gitlint.outputs.exit_code == '0' }} # run only if gitlint run successful
     runs-on: ubuntu-latest
     steps:
+    - name: Create variables
+      id: create_variable
+      run: |
+        REPO=$(echo ${GITHUB_REPOSITORY} | cut -f 2 -d '/')
+        echo "repo=$REPO" >> "$GITHUB_OUTPUT"
     - name: Generate token
       id: generate_token
       uses: actions/create-github-app-token@v2
       with:
         app-id: ${{ secrets.GH_AUTO_APPROVE_APP_ID }}
         private-key: ${{ secrets.GH_AUTO_APPROVE_APP_PRIVATE_KEY }}
-        owner: daedalus-ca
-        repositories: test-auto-approve
+        owner: ${GITHUB_REPOSITORY_OWNER}
+        repositories: ${{ steps.create_variable.outputs.repo }}
     - name: Merge Pull request
       shell: bash
       env:
